[package]
name = "server"
version = "0.1.0"
authors = ["Geordon Worley <vadixidav@gmail.com>"]

[dependencies]
serde = "0.8"
serde_json = "0.8"
serde_macros = "0.8"

[replace]
"aster:0.26.1" = { git = "https://github.com/jchlapinski/aster" }
